title: IN[SCI]TE
name: IN[SCI]TE
email: it@cam.inscite.co
baseurl: "/cambridge" # the subpath of your site, e.g. /blog
url: "http://inscite.co" # the base hostname & protocol for your site
phase: 3 # the phase of the current year's event

# Phase 1 - Before speaker invitations
# Phase 2 - Speaker invitations
# Phase 3 - End of speaker invitations + Ticketing
# Phase 4 - Right before event?
# Phase 5 - Post-event

# Navigation
nav:
  - name:           "committee"
    href:           "/committee"
  - name:           "sponsor"
    href:           "/sponsor"
  - name:           "talk"
    href:           "/talk"
  - name:           "attend"
    href:           "/attend"
  - name:           "2017"
    href:           "/2017"
  - name:           "contact"
    href:           "/contact"


include: ['_pages']

# Build settings
markdown: kramdown
